---
title: "0.1.5.Prepare_Transcript_to_Gene.Rmd"
author: "Gerard Temprano Sagrera"
date: "2023-03-15"
output: html_document
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(openxlsx);library(data.table);library(stringr);library(dplyr)
```


### Load, prepare and save v34 annotation file (used in the quantification made by the company):

```{r}
ann <- fread("C://Users/Gerard/Desktop/AAA/RNAseq/Annotation/gencode.v34.annotation.gtf.gz", header = F, nThread = 6)
```

### Prepare transcript to gene file:

```{r}
trans <- ann[ann$V3 == "transcript",]

# Define regular expressions for gene_id and transcript_id
trans$gene_id <- str_extract(trans$V9, '(?<=gene_id\\s")[ENSG]+\\d+\\.\\d+')
trans$transcript_id <- str_extract(trans$V9, '(?<=transcript_id\\s")[ENST]+\\d+\\.\\d+')

gtf <- trans[,c("transcript_id","gene_id")]

#fwrite(gtf, "C://Users/Gerard/Downloads/TranscriptToGeneV34.txt", sep = "\t")
```





```{r}
# Load annotation file:
ann <- fread("C://Users/Gerard/Desktop/AAA/RNAseq/Annotation/gencode.v26.annotation.gtf.gz", header = F, nThread = 6)
```

### Prepare transcript to gene file:

```{r}
trans <- ann[ann$V3 == "transcript",]

# Define regular expressions for gene_id and transcript_id
trans$gene_id <- str_extract(trans$V9, '(?<=gene_id\\s")[ENSG]+\\d+\\.\\d+')
trans$transcript_id <- str_extract(trans$V9, '(?<=transcript_id\\s")[ENST]+\\d+\\.\\d+')

gtf <- trans[,c("transcript_id","gene_id")]

#fwrite(gtf, "C://Users/Gerard/Downloads/TranscriptToGeneV26.txt", sep = "\t")
```



