---
title: "Ischemic Time GTEx"
author: "Gerard Temprano Sagrera"
date: "2023-01-18"
output: html_document
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(data.table);library(DESeq2);library(stringr);library(ggbiplot);library(dplyr);library(knitr);library(tidyverse);library(data.table);library(edgeR);library(corrr);library(corrplot)
```


### Load TPM counts:

```{r}
tpm <- fread("C://Users/Gerard/Desktop/AAA/RNAseq/Ischemic/gene_reads_2017-06-05_v8_whole_blood.gct.gz")
tpm <- tpm[order(tpm$Name),]

# Save gene names:
gene.names <- tpm$Description

# Format:
tpm <- tpm %>% select(2, 4:ncol(tpm))

tpm <- tpm %>% remove_rownames %>% column_to_rownames(var="Name")
```

### Filter lowely expressed genes:

We apply this filter here, then we will apply LIMMA. Keep genes that have more than 50% of non-zero counts across all samples:
```{r}
keep <- apply(tpm, 1, function(x) sum(x == 0) <= 70)
#sum(keep) # 17,970

tpm <- tpm[keep,]

# Check how this filter affects cases and controls:
#cases.tpm <- tpm[,1:97]
#controls.tpm <- tpm[,98:ncol(tpm)]

#sum(apply(cases.tpm, 1, function(x) sum(x == 0) <= 48)) # 17,884
#sum(apply(controls.tpm, 1, function(x) sum(x == 0) <= 22)) # 17,314
```


### Perform PCA:

```{r}
my_pca <- prcomp((tpm), center = T)
summaryPca <- summary(my_pca)
```

### PCA Plots:

```{r, include=TRUE}
barplot((my_pca$sdev^2 / sum(my_pca$sdev^2))[1:20], names.arg = 1:20,
        xlab = "PC #", ylab = "Amount of explained variance per PC",
        ylim=c(0,0.9), las=2, cex.names=.8)
```

```{r, include=TRUE}
plot(cumsum(my_pca$sdev^2 / sum(my_pca$sdev^2))[1:10], type="b", ylab = "Cummulative proportion of Variance Explained")
```

### PCA Plot:

```{r, include=TRUE}
ggbiplot(my_pca, var.axes = F, obs.scale = 1, var.scale = 1) +
  scale_color_discrete(name = "") +
  theme(legend.direction = "horizontal", legend.position = "top")
```


### Load covariates:

```{r}
sub.covs <- fread("C://Users/Gerard/Desktop/AAA/RNAseq/Ischemic/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt")
sample.covs <- fread("C://Users/Gerard/Desktop/AAA/RNAseq/Ischemic/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")

sample.covs$SMCENTER
# Select Tissue:
sample.covs <- sample.covs[sample.covs$SMTSD == "Whole Blood",]
#sample.covs <- sample.covs[sample.covs$SMTSD == "Artery - Tibial",]
#sample.covs <- sample.covs[sample.covs$SMTSD == "Artery - Aorta",]
#sample.covs <- sample.covs[sample.covs$SMTSD == "Artery - Coronary",]

na.cols <- colnames(sample.covs)[colSums(is.na(sample.covs)) == nrow(sample.covs)]
```


```{r}
sample.covs <- as.data.frame(lapply(sample.covs, as.factor))
sample.covs <- as.data.frame(lapply(sample.covs, as.numeric))

M <- cor(sample.covs[,-9], sample.covs$SMTSISCH, use = "pairwise.complete.obs")
M
```






### Model used previously in GTEx:

```{r}
HardyScale+IschemicTime+RIN+Cohort+NucAcIsoBatch+ExonicRate+PEER1+PEER2+Ancestry+Sex+Age+BMI
```

### Model used in the post-mortem study using GTEx V6:

```{r}
sub.covs$AGE+HGHT+WGHT+BMI+ETHNCTY+sub.covs$SEX+MHCANCERNM+sample.covs$SMRIN+SMTASSCR+SMCAT+sample.covs$SMCENTER+SMTSTPTREF+sample.covs$SMNABTCH+COHORT
```



